title: Ajay.org.uk | Technical Documentation
description: Supporting documentation for some of my projects :) 
remote_theme: just-the-docs

url: https://docs.ajay.org.uk

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
